modLoader = "javafml"
loaderVersion = "[32,)"
license = "GNU LGPLv3"
issueTrackerURL = "https://github.com/Amakazor/TheCurseOfTheSphinx/issues"

[[mods]]
modId = "thecurseofthesphinx"
version = "${version}"
displayName = "The Curse of the Sphinx"
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://ourpoint.com/"
#logoFile="examplemod.png"
#credits="Thanks for this ourpoint mod goes to Java"
authors = "Amakazor, Van Gogh 2, a lot of houseplants and cute kittens"
description = '''
A mod that adds a couple new items, blocks and a boss fight with the Sphinx
'''
[[dependencies.thecurseofthesphinx]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thecurseofthesphinx]]
modId = "forge"
mandatory = true
versionRange = "[32.0.98,)"
ordering = "AFTER"
side = "BOTH"